# Build 
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build 
WORKDIR /src 
COPY ["Inventory.API.csproj", "./"]
RUN dotnet restore 
COPY . .
RUN dotnet publish -c Release -o /app/publish 

# Run 
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8000
ENTRYPOINT ["dotnet", "Inventory.API.dll"]


